# Generated by Django 3.2.20 on 2023-07-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20230719_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Well know actors', 'verbose_name_plural': 'Well know actors'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='On portal'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Header'),
        ),
    ]
